version: "3.9"

services:
  user-management-api:
    container_name: user-management-api
    build:
      context: .                          # یعنی همین فولدر user-management
      dockerfile: src/Docker/Dockerfile   # مسیر نسبی از اینجا
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
